### ISSUE TITLE
Admin Login Password Stored in Plain Text

### ISSUE THREAD

**Issue by gabekole** [binx/beluga#12]
The admin.js file compares input to password in plain text. `req.body.password === process.env.ADMIN_PW` This is a possible security issue, password should be stored as hash and /api/login should hash input server side. I'll fix this myself unless there is something I'm not aware of making my point irrelevant.

**Comment by binx** [comment]
I would love a PR with the fix for this!

**Comment by binx** [comment]
closed with https://github.com/binx/beluga/pull/14
