### ISSUE TITLE
Order ID Undefined?

### ISSUE THREAD

**Issue by amuuth** [binx/beluga#21]
![Screenshot from 2021-01-08 12-20-40](https://user-images.githubusercontent.com/54684365/104045854-2bbe0e80-51ad-11eb-9c91-f69afa3182a6.png)

On adding an item to my cart and checking out, when I click the submit button, the order fails because an order ID is being returned as undefined. Know how I might fix this issue? 

Thanks!

**Comment by binx** [comment]
Hmmmm... seems like something might be off with your Stripe integration. I'd recommend opening the Network tab in your console and seeing if the Stripe API is returning an error.

Here's the part in the Checkout code where the order object should be returned from the Stripe API, and that passed to the Confirm page:
https://github.com/binx/beluga/blob/master/src/components/checkout/CheckoutFlow.js#L70-L86

Here's the server-side call to Stripe as well, if it helps:
https://github.com/binx/beluga/blob/master/server/orders.js#L84-L95
