### ISSUE TITLE
TypeError: product.details.map is not a function

### ISSUE THREAD

**Issue by Brandon4466** [binx/beluga#23]
Hi! No matter what I change on my listing it always goes to this error page. The rest of the website works perfect, including making the list. It's just when I try to view the listing that this error comes up. Have you seen this before? Any idea what I can do to get it working?

Thank you for the help!!

I am running Windows Server 2019, node, yarn, and git are all successfully installed and I restarted after it was done installing. Here is that rest of the error page:

> TypeError: product.details.map is not a function
ProductDetails
C:/beluga/src/components/product/ProductDetails.js:139
  136 | </Right>
  137 | { product.details &&
  138 |   <Details>
> 139 |     <ul>
      | ^  140 |       {product.details.map((detail,i) =>
  141 |         <li key={i}>{detail}</li>
  142 |       )}
View compiled
▼ 23 stack frames were expanded.
renderWithHooks
C:/beluga/node_modules/react-dom/cjs/react-dom.development.js:14985
mountIndeterminateComponent
C:/beluga/node_modules/react-dom/cjs/react-dom.development.js:17811
beginWork
C:/beluga/node_modules/react-dom/cjs/react-dom.development.js:19049
HTMLUnknownElement.callCallback
C:/beluga/node_modules/react-dom/cjs/react-dom.development.js:3945
invokeGuardedCallbackDev
C:/beluga/node_modules/react-dom/cjs/react-dom.development.js:3994
invokeGuardedCallback
C:/beluga/node_modules/react-dom/cjs/react-dom.development.js:4056
beginWork$1
C:/beluga/node_modules/react-dom/cjs/react-dom.development.js:23964
performUnitOfWork
C:/beluga/node_modules/react-dom/cjs/react-dom.development.js:22776
workLoopSync
C:/beluga/node_modules/react-dom/cjs/react-dom.development.js:22707
renderRootSync
C:/beluga/node_modules/react-dom/cjs/react-dom.development.js:22670
performSyncWorkOnRoot
C:/beluga/node_modules/react-dom/cjs/react-dom.development.js:22293
(anonymous function)
C:/beluga/node_modules/react-dom/cjs/react-dom.development.js:11327
unstable_runWithPriority
C:/beluga/node_modules/scheduler/cjs/scheduler.development.js:646
runWithPriority$1
C:/beluga/node_modules/react-dom/cjs/react-dom.development.js:11276
flushSyncCallbackQueueImpl
C:/beluga/node_modules/react-dom/cjs/react-dom.development.js:11322
flushSyncCallbackQueue
C:/beluga/node_modules/react-dom/cjs/react-dom.development.js:11309
batchedUpdates$1
C:/beluga/node_modules/react-dom/cjs/react-dom.development.js:22387
notify
C:/beluga/node_modules/react-redux/es/utils/Subscription.js:19
Subscription.notifyNestedSubs
C:/beluga/node_modules/react-redux/es/utils/Subscription.js:90
Subscription.handleChangeWrapper
C:/beluga/node_modules/react-redux/es/utils/Subscription.js:95
dispatch
C:/beluga/node_modules/redux/es/redux.js:222
(anonymous function)
C:/beluga/node_modules/redux-thunk/es/index.js:11
(anonymous function)
C:/beluga/node_modules/connected-react-router/esm/middleware.js:22
▲ 23 stack frames were expanded.
(anonymous function)
C:/beluga/src/App.js:50
  47 |    fetch('/user/')
  48 |      .then(res => res.json())
  49 |      .then(result => {
> 50 |        dispatch({ type: "SET_ADMIN", isAdmin: result.isAdmin })
     | ^  51 |      })
  52 |  }, []);
  53 | 
View compiled

**Comment by binx** [comment]
hmmmm! My guess is something went awry in your `src/assets/store_config.json` file. Look at the `products` array, whichever product isn't showing up seems like it has a key `details` that isn't an array. Hopefully that's the issue? You should either be able to set that as an empty array, or delete the key from your project object.

FYI the "details" key renders a list of bullet points on the project display page.

Hope that helps! If that doesn't work still, could you please paste when's listed in the `products` key of your `store_config.json`?
