### ISSUE TITLE
Viewing product throws error

### ISSUE THREAD

**Issue by streamerd** [binx/beluga#32]
Hi,

After installation and config, adding a new product as well; 

viewing a product is throwing an error as such:
```

TypeError: product.details.map is not a function
ProductDetails
src/components/product/ProductDetails.js:140
  137 | </Right>
  138 | { product.details &&
  139 |   <Details>
> 140 |     <ul>
      | ^  141 |       {product.details.map((detail,i) =>
  142 |         <li key={i}>{detail}</li>
  143 |       )}
```

to reproduce this error, create a product (eg slug with "asdf") and click on it on /shop, 
then expect to redirect to the error page for that specific product.

eg. http://localhost:3000/product/asdf

node version: v14.0.0
Bests,
@

**Comment by SeanTaiGordon** [comment]
Looks exactly like this closed issue - https://github.com/binx/beluga/issues/23. I would check that you entered the correct Stripe keys and that your `src/assets/store_config.json` has the correct product details array.
