### ISSUE TITLE
failed to compile 

### ISSUE THREAD

**Issue by wvfrm** [binx/beluga#50]
build time error
./src/data/store.js
Module not found: Your application tried to access history, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

**Comment by binx** [comment]
Have you tried to manually add the `history` package?
`yarn add history`

**Comment by wvfrm** [comment]
yes, it resolved i had to install all the dependencies again but now i'm getting an unhandled rejection (error) crossorgin-error ?

**Comment by binx** [comment]
Do you have the node server running as well?

**Comment by wvfrm** [comment]
yes !

**Comment by binx** [comment]
What's the error showing up in the Network > Response tab?

**Comment by wvfrm** [comment]
304
