### ISSUE TITLE
Change currency

### ISSUE THREAD

**Issue by MindSetFPS** [binx/beluga#7]
Hi, i like your project and I was testing and i was wondering if you could explain how to change the currency.

**Comment by binx** [comment]
Hi there! So first off when you sign up for Stripe, you can set the currency of your choice. From there I would fork this project, and switch out the currency symbols. Stripe will make sure to process the correct currency.

You'll need to modify each instance of
`.toLocaleString('en-US', { style: 'currency', currency: 'USD' });`
and on the Stripe API calls, switch out
`currency: 'usd',`

Hope that helps!
